[project]
name = "maia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.139.0",
    "uvicorn>=0.50.2",
    "httpx2",
    "python-dotenv>=1.2.2",
    "faster-whisper>=1.2.1",
    "soundfile>=0.14.0",
    "torch>=2.13.0",
    "pocket-tts>=2.1.0",
    "emoji>=2.15.0",
    "kokoro>=0.9.4",
    "torchaudio>=2.11.0",
    "pyloudnorm>=0.2.0",
    "requests>=2.34.2",
    "numpy>=2.4.6",
]

[project.scripts]
maia = "maia.app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.deptry]
ignore = ["python-dotenv", "maia"]
