TOOL_DESCRIPTIONS = {
    "browser_exec": "J'utilise un navigateur web",
    "clarify": "Je te pose une question pour préciser",
    "computer_use": "J'utilise le contrôle du bureau",
    "cronjob": "Je gère une tâche planifiée",
    "delegate_task": "Je délègue une tâche à un sous-agent",
    "memory": "J'enregistre une information en mémoire",
    "patch": "Je modifie un fichier avec précision",
    "process": "Je gère un processus en arrière-plan",
    "read_file": "Je lis le contenu d'un fichier",
    "search_files": "Je recherche dans les fichiers",
    "session_search": "Je recherche dans nos sessions passées",
    "skill_manage": "Je gère un skill",
    "skill_view": "J'utilise un skill",
    "skills_list": "J'affiche la liste des skills",
    "terminal": "J'exécute une commande système",
    "todo": "Je mets à jour ma liste de tâches",
    "vision_analyze": "J'analyse une image",
    "web_extract": "Je récupère du contenu sur internet",
    "web_search": "Je fais une recherche sur le web",
    "write_file": "Je crée ou modifie un fichier",
}
